---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Me dice la cantidad de reservas de un libro
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Me dice la suma de la cantidad de reservas de todas las bibliotecas
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Me dice la suma de la cantidad de reservas de una biblioteca específica
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ninguna de las anteriores
  checked: false
name: "¿Qué hace esto?"
