---
locale: es
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Biblioteca
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Libro
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Novela
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Divulgación
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: LibroDeCuentos
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Todas las anteriores
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ninguna de las anteriores
  checked: false
name: Herencia de Libro
